# Generated by Django 4.1.2 on 2026-01-04 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ven_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('protocol', models.CharField(choices=[('2.0b', 'OpenADR 2.0b'), ('3.0', 'OpenADR 3.0')], default='2.0b', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('security_token', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VEN',
                'verbose_name_plural': 'VENs',
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(default='POWER_REAL', max_length=50)),
                ('value', models.FloatField()),
                ('ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='back.ven')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('signal_name', models.CharField(default='SIMPLE', max_length=50)),
                ('payload', models.FloatField()),
                ('status', models.CharField(choices=[('far', 'Far'), ('near', 'Near'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='far', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='back.ven')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
